### ISSUE TITLE
Issues with structs as variables

### ISSUE THREAD

**Issue by hoshsadiq** [maja42/goval#5]
Hello,

I'm trying to use this library as I prefer it over Knetic's library based on features described, however, I'm struggling to get this working with structs. Consider the following scenario.
```go
type Testing struct {
	Title string
}
obj := &Testing{Title: "hello"}
eval := goval.NewEvaluator()
newrs, err := eval.Evaluate(`obj.Title == "hello"`, map[string]interface{}{"obj": obj}, nil)
# err == "syntax error: cannot access fields on type <unknown type>"
fmt.Printf(newrs.(string))
```

Where this scenario works fine:
```go
type Testing struct {
	Title string
}
//obj := &Testing{Title: "hello"}
eval := goval.NewEvaluator()
newrs, err := eval.Evaluate(`obj == "hello"`, map[string]interface{}{"obj": "hello"}, nil)
fmt.Printf(newrs.(string))
```

Any ideas how I can resolve this?

**Comment by maja42** [comment]
I tried to implement support for structs in this library, but eventually stopped working on it.
While it is easily possible to add basic support for structs, it creates a lot of loose ends and edge cases.

It would need to deal with pointers, interfaces, unexported members, member functions, nil-values, empty structs and so on. It would also need to integrate with already existing types like objects (maps) and arrays interchangably. If there are any edge-cases that aren't handled intuitively (and there will be a lot), the behaviour would need to be documented.

The thing I like most about this library compared to others is that the grammar is well-defined for all cases, and the existing types play together neatly. The whole syntax is easy to understand and won't cause suprises in the long run.

If you want to have struct-support, I'd recomment forking this package and taking a different approach. Currently, the expression is evaluated while being parsed by the lexer. To deal with the additional complexity, a better approach is to create an intermediate AST from the input and evaluate it afterwards. 
This would reduce complexity in the yacc file and the actual logic can be written in go.
It would also allow more "sophisticated" syntax like a ternery operator or boolean operators that don't evaluate every component once the outcome is already clear (`a() && b()` will always call both functions, even if `a` returned false).

**Comment by maja42** [comment]
Unfortunately, structs are not supported by this library right now, and I'm not planning to add support for it in the near future. 
To add support for structs, a different approach would be needed (creating an AST instead of evaluating-while-parsing). See my comment on #6.
